import BigNumber from "bignumber.js";
import { getCryptoCurrencyById } from "@ledgerhq/cryptoassets/currencies";
import {
  accountUserDataExportSelector,
  initialState as liveWalletInitialState,
} from "@ledgerhq/live-wallet/store";
import { genAccount } from "@ledgerhq/live-common/mock/account";
import { genTokenAccount } from "@ledgerhq/ledger-wallet-framework/mocks/account";
import { emptyHistoryCache } from "@ledgerhq/ledger-wallet-framework/account";
import type { Account, AccountUserData, Operation, TokenAccount } from "@ledgerhq/types-live";
import type { TokenCurrency } from "@ledgerhq/types-cryptoassets";
import { initAccounts } from "~/renderer/actions/accounts";

// ─── Exact balances ──────────────────────────────────────────────────────────
const BTC_BALANCE      = new BigNumber(16_330_000);     // 0.1633 BTC  (8 dec)
const TRX_BALANCE      = new BigNumber(288_430_000);    // 288.43 TRX  (6 dec)
const USDT_BALANCE     = new BigNumber("12135700000");  // 12,135.7 USDT (6 dec)
const USDC_BALANCE     = new BigNumber("118500000");    // 118.5 USDC   (6 dec)
const SWAP_USDT_AMOUNT = new BigNumber("4900000000");   // 4,900 USDT
const SWAP_BTC_AMOUNT  = new BigNumber(16_330_000);     // 0.1633 BTC (the full balance came from swap)

// April 20, 2025 timestamps
const APR_20_IN   = new Date("2025-04-20T09:00:00.000Z");
const APR_20_SWAP = new Date("2025-04-20T12:00:00.000Z");

// Stable operation IDs (used to link swapHistory → operation)
const BTC_SWAP_IN_ID  = "preset-btc-swap-in-20250420";
const USDT_IN_ID      = "preset-usdt-in-20250420";
const USDT_SWAP_ID    = "preset-usdt-swap-out-20250420";

// Realistic-looking external addresses
// TRX: 34-char Base58 starting with T
const ADDR_TRX_SENDER   = "TCzWzMvHZXfZFNWVQEEkGn9RNMhKJmxKPX"; // external wallet sending USDT in
const ADDR_TRX_EXCHANGE = "TKVyMDssaXKBUFnm4KcUKyQEXQPGEJsJkZ"; // Changelly TRX deposit address
// BTC: P2SH address starting with 3 (exchange hot wallet)
const ADDR_BTC_EXCHANGE = "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy";

function makeOp(
  accountId: string,
  id: string,
  type: "IN" | "OUT",
  value: BigNumber,
  date: Date,
  blockHeight: number,
  sender: string,
  recipient: string,
): Operation {
  return {
    id,
    hash: id.padEnd(64, "0"),
    type,
    value,
    fee: new BigNumber(0),
    senders: [sender],
    recipients: [recipient],
    blockHash: id.padEnd(64, "0"),
    blockHeight,
    accountId,
    date,
    extra: {},
  };
}

// Build TokenCurrency objects inline so we don't depend on async API lookups.
function buildTronToken(
  id: string,
  contractAddress: string,
  name: string,
  ticker: string,
): TokenCurrency {
  const tronCurrency = getCryptoCurrencyById("tron");
  return {
    type: "TokenCurrency",
    id,
    contractAddress,
    name,
    ticker,
    tokenType: "trc20",
    parentCurrency: tronCurrency,
    units: [{ name: ticker, code: ticker, magnitude: 6 }],
  };
}

const USDT_TOKEN = buildTronToken(
  "tron/trc20/tr7nhqjekqxgtci8q8zy4pl8otszgjlj6t",
  "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
  "Tether USD",
  "USDT",
);

const USDC_TOKEN = buildTronToken(
  "tron/trc20/tekxitehnzsmse2xqrbj4w32run966rdz8",
  "TEkxiTehnzSmSe2XqrBj4w32RUN966rdz8",
  "USDCoin",
  "USDC",
);

function buildTokenAccount(
  index: number,
  parent: Account,
  token: TokenCurrency,
  balance: BigNumber,
  operations: Operation[],
  swapHistory: TokenAccount["swapHistory"],
): TokenAccount {
  const acc = genTokenAccount(index, parent, token);
  // Wipe all random operations generated by genTokenAccount
  acc.operations      = operations;
  acc.operationsCount = operations.length;
  acc.balance          = balance;
  acc.spendableBalance = balance;
  acc.swapHistory      = swapHistory;
  acc.creationDate     = operations.length > 0
    ? operations[operations.length - 1].date
    : new Date();
  acc.balanceHistoryCache = emptyHistoryCache;
  return acc;
}

export function buildPresetAccounts(): [Account, AccountUserData][] {
  const btcCurrency  = getCryptoCurrencyById("bitcoin");
  const tronCurrency = getCryptoCurrencyById("tron");

  // ── BTC account ───────────────────────────────────────────────────────────
  // One IN operation: the BTC received from the April 20 swap
  const btcAccount = genAccount("preset-btc-1", { currency: btcCurrency, operationsSize: 0 });
  btcAccount.balance          = BTC_BALANCE;
  btcAccount.spendableBalance = BTC_BALANCE;

  const btcSwapIn = makeOp(
    btcAccount.id,
    BTC_SWAP_IN_ID,
    "IN",
    SWAP_BTC_AMOUNT,
    APR_20_SWAP,
    btcAccount.blockHeight - 10,
    ADDR_BTC_EXCHANGE,        // sender: Changelly BTC hot wallet
    btcAccount.freshAddress,  // recipient: user's own BTC address
  );
  btcAccount.operations       = [btcSwapIn];
  btcAccount.operationsCount  = 1;
  btcAccount.creationDate     = APR_20_SWAP;
  btcAccount.balanceHistoryCache = emptyHistoryCache;

  // ── TRX account ───────────────────────────────────────────────────────────
  const tronAccount = genAccount("preset-trx-1", {
    currency: tronCurrency,
    operationsSize: 0,
    subAccountsCount: 0,
  });
  tronAccount.balance          = TRX_BALANCE;
  tronAccount.spendableBalance = TRX_BALANCE;
  tronAccount.operations       = [];
  tronAccount.operationsCount  = 0;
  tronAccount.balanceHistoryCache = emptyHistoryCache;

  // USDT subaccount — 2 exact operations + swapHistory
  const usdtAcc = buildTokenAccount(
    0,
    tronAccount,
    USDT_TOKEN,
    USDT_BALANCE,
    [
      // Most-recent first
      makeOp(tronAccount.id + "|0", USDT_SWAP_ID, "OUT", SWAP_USDT_AMOUNT, APR_20_SWAP, tronAccount.blockHeight - 9,
        tronAccount.freshAddress, // sender: user's own TRX/USDT address
        ADDR_TRX_EXCHANGE,        // recipient: Changelly TRX deposit address
      ),
      makeOp(tronAccount.id + "|0", USDT_IN_ID, "IN", SWAP_USDT_AMOUNT, APR_20_IN, tronAccount.blockHeight - 10,
        ADDR_TRX_SENDER,          // sender: external wallet
        tronAccount.freshAddress, // recipient: user's own TRX/USDT address
      ),
    ],
    [
      {
        provider: "changelly",
        swapId: "preset-swap-20250420",
        status: "finished",
        receiverAccountId: btcAccount.id,
        operationId: USDT_SWAP_ID,
        fromAmount: SWAP_USDT_AMOUNT,
        toAmount: SWAP_BTC_AMOUNT,
      },
    ],
  );

  // USDC subaccount — balance only, no transactions
  const usdcAcc = buildTokenAccount(1, tronAccount, USDC_TOKEN, USDC_BALANCE, [], []);

  tronAccount.subAccounts = [usdtAcc, usdcAcc];

  const btcUserData  = accountUserDataExportSelector(liveWalletInitialState, { account: btcAccount });
  const tronUserData = accountUserDataExportSelector(liveWalletInitialState, { account: tronAccount });

  return [
    [btcAccount, btcUserData],
    [tronAccount, tronUserData],
  ];
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function injectPresetAccounts(store: { dispatch: (action: any) => void }): void {
  const accounts = buildPresetAccounts();
  store.dispatch(initAccounts(accounts));
  console.log("[preset] Injected:", accounts.map(([a]) => a.id));
}
